name: Dev prerelease

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch (forced to dev)'
        required: true
        type: string
        default: 'dev'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/heads/dev')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev

      - name: Setup Node.js 22.18.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}